name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # You might consider updating this to 18 or 20 if your project supports it

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3 # Updated from v2
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 # Updated from v2